homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 576
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Bucharest
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes:
    darkblue:
      primary-color: "#396FB6"
      light-primary-color: "#77a0d4"
      dark-primary-color: "#3539ce"
      text-primary-color: "#ffffff"
      primary-background-color: "#37464f"
      sidebar-text_-_background: "#3c4348"
      paper-card-background-color: "#263137"
      paper-card-header-color: "var(--text-primary-color)"
      secondary-background-color: "var(--primary-background-color)"
      primary-text-color: "var(--text-primary-color)"
      secondary-text-color: "var(--primary-color)"
      paper-listbox-background-color: "var(--sidebar-text_-_background)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-bar-color: "var(--dark-primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-slider-container-color: "var(--sidebar-text_-_background)"
      paper-progress-secondary-color: "var(--sidebar-text_-_background)"
      paper-item-selected_-_background-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--text-primary-color)"
      paper-item-icon-color: "var(--text-primary-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-grey-50: "var(--sidebar-text_-_background)"
      paper-grey-200: "var(--primary-background-color)"
      label-badge-background-color: "var(--sidebar-text_-_background)"
      label-badge-text-color: "var(--text-primary-color)"
      label-badge-red: "var(--primary-color)"
      label-badge-blue: "var(--light-primary-color)"
      label-badge-green: "var(--dark-primary-color)"
      label-badge-yellow: "var(--text-primary-color)"
      label-badge-grey: "var(--paper-grey-500)"
      table-row-background-color: "var(--paper-card-background-color)"
      table-row-alternative-background-color: "var(--sidebar-text_-_background)"

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - weather
      - weather_1d_metric
      - temp_c
      - temp_low_1d_c
      - temp_high_1d_c
      - precip_1d
      - wind_kph
  - platform: time_date
    display_options:
      - time
      - date
  - platform: broadlink_power
    name: sp3_watt
    host: 192.168.1.30
    mac: !secret broadlink_sp3_1_mac

# Text to speech
tts:
  - platform: google
    language: 'ro'

# Cloud
#cloud:

# Wake on lan
wake_on_lan:

# iOS App
ios:

ifttt:
  key: !secret ifttt_key

recorder:
  include:
    entities:
      input_boolean.alarm_set

input_boolean:
  alarm_set:
    name: Alarma
    icon: mdi:security-home

zone:
  - name: rond_cartier
    latitude: !secret zone_rond_latitude
    longitude: !secret zone_rond_longitude
    icon: mdi:bullseye
    radius: 100
  - name: home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    icon: mdi:home
    radius: 150

#light:
#  - platform: yeelight
#    devices:
#      192.168.1.35:
#        name: Hollway
#        save_on_change: True

media_player:
  - platform: braviatv
    host: 192.168.1.20    
  - platform: kodi
    host: 192.168.1.20    
    name: Kodi Living
    username: kodi
    password: kodi
  - platform: kodi
    host: 192.168.1.21    
    name: Kodi Dormitor
    username: kodi
    password: kodi    
  - platform: webostv
    host: 192.168.1.22
    name: WebOs TV Dormitor
    timeout: 5

xiaomi_aqara:
  discovery_retry: 5  
  gateways:
    - mac: !secret aqara_mac
      key: !secret aqara_key
      host: 192.168.1.34
     
notify:
  - platform: nfandroidtv
    name: Sony Bravia TV
    host: 192.168.1.20
  - platform: webostv
    name: webos_tv
    host: 192.168.1.22    
    filename: webostv.conf
    icon: "bell.png"
  - platform: telegram
    name: telegram_liviu
    chat_id: !secret telegram_chat_id_liviu
  - platform: telegram
    name: telegram_carmen
    chat_id: !secret telegram_chat_id_carmen    
  - name: all_phones
    platform: group
    services:
      - service: telegram_liviu
      - service: telegram_carmen
  - name: all_phones_ios
    platform: group
    services:
      - service: ios_iphone__liviu
      - service: ios_iphone__carmen
  - name: all_tv
    platform: group
    services:
      - service: sony_bravia_tv
        data:
          title: "Home Assistant"
      - service: webos_tv
        data:
          title: "Home Assistant"

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_liviu
      - !secret telegram_chat_id_carmen

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    consider_home: 0:30
    username: !secret router_user
    password: !secret router_password

switch: !include switches.yaml    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
